language: csharp
solution: BinaryRelations.sln
mono: none
dotnet: 3.1.402
script:
 - dotnet restore
 - dotnet test BinaryRelationsTests/BinaryRelationsTests.csproj
after_script:
 - bash <(curl -s https://codecov.io/bash)
