language: csharp
solution: BinaryRelations.sln
mono: none
dotnet: 3.1.402
script:
 - dotnet restore
 - dotnet test -c Release BinaryRelationsTests/BinaryRelationsTests.csproj  --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
 - bash <(curl -s https://codecov.io/bash)
