name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Update NuGet package
      uses: actions/setup-dotnet@v1
      with:
          source-url: https://nuget.pkg.github.com/MaxRev-Dev/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.PACKAGE_TOKEN}}        

    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o ./BinaryRelations/out  
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./BinaryRelations/out/*.nupkg --skip-duplicate --no-symbols true
